[package]

name = "get_errno"
version = "0.0.3"
authors = ["Jakub Stasiak <jakub@stasiak.at>"]
license = "MIT"
description = "Extracting errno from std::io::Error"
readme = "README.md"
repository = "https://github.com/jstasiak/rust-get_errno"


[dependencies]
regex = "*"
regex_macros = "*"
